installing_message = "Reminder: yuzu is an <b>experimental</b> emulator. Stuff will break!"
hide_advanced = true

[[packages]]
name = "yuzu Mainline"
description = "The mainline version of yuzu is the standard distribution of yuzu."
    [packages.source]
    name = "github"
    match = "^yuzu-windows-mingw-[0-9]*-[0-9a-f]*.zip$"
        [packages.source.config]
        repo = "yuzu-emu/yuzu-canary"
    [[packages.shortcuts]]
    name = "yuzu Mainline"
    relative_path = "canary-mingw/yuzu.exe"
    description = "Launch yuzu (Mainline version)"
