installing_message = "Reminder: yuzu is an <b>experimental</b> emulator. Stuff will break!"
new_tool = "https://raw.githubusercontent.com/j-selby/test-installer/master/liftinstall5.exe"

[[packages]]
name = "yuzu Nightly"
description = "The nightly build of yuzu contains already reviewed and tested features."
    [packages.source]
    name = "github"
    match = "^yuzu-windows-mingw-[0-9]*-[0-9a-f]*.zip$"
        [packages.source.config]
        repo = "yuzu-emu/yuzu-nightly"
    [[packages.shortcuts]]
    name = "yuzu Nightly"
    relative_path = "nightly-mingw/yuzu.exe"
    description = "Launch yuzu (Nightly version)"

[[packages]]
name = "yuzu Canary"
description = "The canary build of yuzu has additional features that are still waiting on review."
    [packages.source]
    name = "github"
    match = "^yuzu-windows-mingw-[0-9]*-[0-9a-f]*.zip$"
        [packages.source.config]
        repo = "yuzu-emu/yuzu-canary"
    [[packages.shortcuts]]
    name = "yuzu Canary"
    relative_path = "canary-mingw/yuzu.exe"
    description = "Launch yuzu (Canary version)"

[[packages]]
name = "Test package"
description = "Just a testing package"
default = true
    [packages.source]
    name = "github"
    match = "^TestPackage.zip$"
        [packages.source.config]
        repo = "j-selby/test-installer"
