installing_message = "Reminder: yuzu is an <b>experimental</b> emulator. Stuff will break!"
hide_advanced = true

[[packages]]
name = "yuzu"
description = "Includes frequent updates to yuzu with all the latest reviewed and tested features."
default = true
    [packages.source]
    name = "github"
    match = "^yuzu-windows-msvc-[0-9]*-[0-9a-f]*.zip$"
        [packages.source.config]
        repo = "yuzu-emu/yuzu-mainline"
    [[packages.shortcuts]]
    name = "yuzu"
    relative_path = "yuzu-windows-msvc/yuzu.exe"
    description = "Launch yuzu"
